[package]
name = "xvfs-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true
description = "Protobuf definitions and generated gRPC clients and servers"

[dependencies]
xvfs-types = { workspace = true }

[lints]
workspace = true
