//! Request identifiers, tracing setup, and metrics.
//!
//! PLAN.md M1.1 asks for "structured error codes, request IDs, tracing, metrics,
//! and redaction". The error codes live in `gfs-types`, redaction in
//! `gfs_types::redact`, and the rest here.
//!
//! The one non-obvious decision: a request ID is generated by the server when the
//! client does not supply one, and a client-supplied one is **validated** before
//! use. An unvalidated client string that reaches every log line for a request is a
//! log-injection primitive with unusually good reach.

use std::sync::atomic::{AtomicU64, Ordering};

/// The header and gRPC metadata key carrying a request ID.
pub const REQUEST_ID_KEY: &str = "x-request-id";

/// A request identifier, safe to log.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RequestId(String);

impl RequestId {
  /// Generate a fresh identifier.
  ///
  /// A process-unique prefix plus a counter, rather than a random value per
  /// request: the counter makes two lines from the same process orderable, and the
  /// prefix keeps IDs from two processes distinct. Neither property needs
  /// randomness, and reading `/dev/urandom` per request would be a syscall on the
  /// hot path for no benefit.
  pub fn generate() -> Self {
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    static PREFIX: std::sync::OnceLock<String> = std::sync::OnceLock::new();
    let prefix = PREFIX.get_or_init(|| {
      crate::util::random_hex(4).unwrap_or_else(|_| format!("{:08x}", std::process::id()))
    });
    let n = COUNTER.fetch_add(1, Ordering::Relaxed);
    RequestId(format!("{prefix}-{n:012x}"))
  }

  /// Accept a client-supplied identifier, or generate one.
  ///
  /// A client ID is accepted only if it is short and consists of characters that
  /// cannot forge a log record or a field boundary. Anything else is replaced
  /// rather than sanitized: a request whose ID was silently rewritten is harder to
  /// correlate than one that simply got a server ID.
  pub fn from_client(supplied: Option<&str>) -> Self {
    match supplied {
      Some(s)
        if !s.is_empty()
          && s.len() <= 64
          && s
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_' || b == b'.') =>
      {
        RequestId(s.to_owned())
      }
      _ => RequestId::generate(),
    }
  }

  pub fn as_str(&self) -> &str {
    &self.0
  }
}

impl std::fmt::Display for RequestId {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    f.write_str(&self.0)
  }
}

/// Initialize tracing from `RUST_LOG`, defaulting to `info`.
///
/// JSON when `GFS_LOG_FORMAT=json`, human-readable otherwise. Idempotent, so
/// tests and the binary can both call it.
pub fn init_tracing() {
  use tracing_subscriber::prelude::*;

  let filter = tracing_subscriber::EnvFilter::try_from_default_env()
    .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info"));

  let json = std::env::var("GFS_LOG_FORMAT").is_ok_and(|v| v == "json");
  let registry = tracing_subscriber::registry().with(filter);
  // `try_init` rather than `init`: a second call in a test process must not panic.
  if json {
    let _ = registry
      .with(tracing_subscriber::fmt::layer().json())
      .try_init();
  } else {
    let _ = registry.with(tracing_subscriber::fmt::layer()).try_init();
  }
}

/// Metric names, in one place so a dashboard and the code cannot drift.
pub mod metric {
  pub const REQUESTS: &str = "gfs_requests_total";
  pub const REQUEST_DURATION: &str = "gfs_request_duration_seconds";
  pub const BLOB_BYTES_SERVED: &str = "gfs_blob_bytes_served_total";
  pub const TREE_CACHE_HITS: &str = "gfs_tree_cache_hits_total";
  pub const TREE_CACHE_MISSES: &str = "gfs_tree_cache_misses_total";
  pub const LEASES_ACTIVE: &str = "gfs_leases_active";
  pub const LEASES_IN_GRACE: &str = "gfs_leases_in_grace";
  pub const LEASE_RENEWAL_FAILURES: &str = "gfs_lease_renewal_failures_total";
}

/// Record the outcome of one request.
///
/// Labelled by action and error code, never by repository or subject. High
/// cardinality is the obvious reason; the better one is DESIGN.md section 10 item
/// 8, which requires metrics to be partitioned so object existence is not leaked
/// across tenants -- and a per-repository counter series is itself an existence
/// oracle for anyone who can read the metrics endpoint.
pub fn record_request(
  action: &'static str,
  code: Option<gfs_types::ErrorCode>,
  elapsed: std::time::Duration,
) {
  let outcome = if code.is_none() { "ok" } else { "error" };
  let error_code = code.map(|c| c.as_str()).unwrap_or("none");
  metrics::counter!(metric::REQUESTS, "action" => action, "outcome" => outcome, "code" => error_code)
    .increment(1);
  metrics::histogram!(metric::REQUEST_DURATION, "action" => action).record(elapsed.as_secs_f64());
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn generated_request_ids_are_unique_and_ordered_within_a_process() {
    let a = RequestId::generate();
    let b = RequestId::generate();
    assert_ne!(a, b);
    // Same prefix, increasing counter, so two lines from one process sort.
    let (pa, na) = a.as_str().rsplit_once('-').unwrap();
    let (pb, nb) = b.as_str().rsplit_once('-').unwrap();
    assert_eq!(pa, pb);
    assert!(na < nb);
  }

  #[test]
  fn a_client_request_id_that_could_forge_a_log_record_is_replaced() {
    // The reach is what makes this worth validating: a request ID appears on every
    // line for that request.
    for hostile in [
      "ok\nlevel=ERROR msg=forged",
      "has space",
      "quote\"inside",
      "tab\there",
      "\u{1b}[2Jclear",
      "",
      &"x".repeat(65),
    ] {
      let id = RequestId::from_client(Some(hostile));
      assert_ne!(id.as_str(), hostile, "{hostile:?} must not be adopted");
      assert!(id
        .as_str()
        .bytes()
        .all(|b| b.is_ascii_alphanumeric() || b == b'-'));
    }
  }

  #[test]
  fn a_reasonable_client_request_id_is_preserved_for_correlation() {
    // Preserving it is the point: the client's trace and the server's have to join.
    for ok in ["abc123", "trace-0f3a.1", "req_42"] {
      assert_eq!(RequestId::from_client(Some(ok)).as_str(), ok);
    }
  }

  #[test]
  fn an_absent_client_request_id_yields_a_generated_one() {
    assert!(!RequestId::from_client(None).as_str().is_empty());
  }
}
