[package]
name = "xvfs-search"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true
description = "Revision-aware search indexing and query library"

[dependencies]
xvfs-types = { workspace = true }

[lints]
workspace = true
