[package]
name = "xvfs-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true
description = "The xvfs user and orchestrator command-line interface"

[[bin]]
name = "xvfs"
path = "src/main.rs"

[dependencies]
xvfs-types = { workspace = true }
xvfs-proto = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true, features = ["client", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }

[lints]
workspace = true
